server:
  port: 9899
spring:
  application:
    name: JobNotification
  datasource:
    url: jdbc:mysql://localhost:3306/JobNotificationInfo
    username: root
    password: Abinaya@2003
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true